final List<Map<String, dynamic>> alphabets = [
  {
    "letter": "A",
    "leftImage": "assets/alphabets/A.png",
    "rightImage": "assets/alphabetsImages/apple.png",
    "soundPath": "assets/phonicsSound/apple.mp3",
    "quizOptions": [
      {"text": "A", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "B",
    "leftImage": "assets/alphabets/B.png",
    "rightImage": "assets/alphabetsImages/ball.png",
    'soundPath': 'assets/phonicsSound/ball.mp3',
    "quizOptions": [
      {"text": "B", "isCorrect": true},
      {"text": "A", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "C",
    "leftImage": "assets/alphabets/C.png",
    "rightImage": "assets/alphabetsImages/cat.png",
    'soundPath': 'assets/phonicsSound/cat.mp3',
    "quizOptions": [
      {"text": "C", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "E", "isCorrect": false},
    ],
  },
  {
    "letter": "D",
    "leftImage": "assets/alphabets/D.png",
    "rightImage": "assets/alphabetsImages/dog.png",
    'soundPath': 'assets/phonicsSound/dog.mp3',
    "quizOptions": [
      {"text": "D", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "E",
    "leftImage": "assets/alphabets/E.png",
    "rightImage": "assets/alphabetsImages/elephant.png",
    'soundPath': 'assets/phonicsSound/elephant.mp3',
    "quizOptions": [
      {"text": "E", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "F",
    "leftImage": "assets/alphabets/F.png",
    "rightImage": "assets/alphabetsImages/fish.png",
    'soundPath': 'assets/phonicsSound/fish.mp3',
    "quizOptions": [
      {"text": "F", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "G",
    "leftImage": "assets/alphabets/G.png",
    "rightImage": "assets/alphabetsImages/goat.png",
    'soundPath': 'assets/phonicsSound/goat.mp3',
    "quizOptions": [
      {"text": "G", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "H",
    "leftImage": "assets/alphabets/H.png",
    "rightImage": "assets/alphabetsImages/horse.png",
    'soundPath': 'assets/phonicsSound/horse.mp3',
    "quizOptions": [
      {"text": "H", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "I",
    "leftImage": "assets/alphabets/I.png",
    "rightImage": "assets/alphabetsImages/ice-cream.png",
    'soundPath': 'assets/phonicsSound/ice_cream.mp3',
    "quizOptions": [
      {"text": "I", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "J",
    "leftImage": "assets/alphabets/J.png",
    "rightImage": "assets/alphabetsImages/jug.png",
    'soundPath': 'assets/phonicsSound/jug.mp3',
    "quizOptions": [
      {"text": "J", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "K",
    "leftImage": "assets/alphabets/K.png",
    "rightImage": "assets/alphabetsImages/kite.png",
    'soundPath': 'assets/phonicsSound/kite.mp3',
    "quizOptions": [
      {"text": "K", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "L",
    "leftImage": "assets/alphabets/L.png",
    "rightImage": "assets/alphabetsImages/light.png",
    'soundPath': 'assets/phonicsSound/light.mp3',
    "quizOptions": [
      {"text": "L", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "M",
    "leftImage": "assets/alphabets/M.png",
    "rightImage": "assets/alphabetsImages/monkey.png",
    'soundPath': 'assets/phonicsSound/monkey.mp3',
    "quizOptions": [
      {"text": "M", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "N",
    "leftImage": "assets/alphabets/N.png",
    "rightImage": "assets/alphabetsImages/nest.png",
    'soundPath': 'assets/phonicsSound/nest.mp3',
    "quizOptions": [
      {"text": "N", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },

  {
    "letter": "O",
    "leftImage": "assets/alphabets/O.png",
    "rightImage": "assets/alphabetsImages/owl.png",
    'soundPath': 'assets/phonicsSound/owl.mp3',
    "quizOptions": [
      {"text": "O", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "P",
    "leftImage": "assets/alphabets/P.png",
    "rightImage": "assets/alphabetsImages/parrot.png",
    'soundPath': 'assets/phonicsSound/parrot.mp3',
    "quizOptions": [
      {"text": "P", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "Q",
    "leftImage": "assets/alphabets/Q.png",
    "rightImage": "assets/alphabetsImages/queen.png",
    'soundPath': 'assets/phonicsSound/queen.mp3',
    "quizOptions": [
      {"text": "Q", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "R",
    "leftImage": "assets/alphabets/R.png",
    "rightImage": "assets/alphabetsImages/rabbit.png",
    'soundPath': 'assets/phonicsSound/rabbit.mp3',
    "quizOptions": [
      {"text": "R", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "S",
    "leftImage": "assets/alphabets/S.png",
    "rightImage": "assets/alphabetsImages/snake.png",
    'soundPath': 'assets/phonicsSound/snake.mp3',
    "quizOptions": [
      {"text": "S", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },

  {
    "letter": "T",
    "leftImage": "assets/alphabets/T.png",
    "rightImage": "assets/alphabetsImages/tree.png",
    'soundPath': 'assets/phonicsSound/tree.mp3',
    "quizOptions": [
      {"text": "T", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "U",
    "leftImage": "assets/alphabets/U.png",
    "rightImage": "assets/alphabetsImages/umbrella.png",
    'soundPath': 'assets/phonicsSound/umbrella.mp3',
    "quizOptions": [
      {"text": "U", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "V",
    "leftImage": "assets/alphabets/V.png",
    "rightImage": "assets/alphabetsImages/violin.png",
    'soundPath': 'assets/phonicsSound/violin.mp3',
    "quizOptions": [
      {"text": "V", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "W",
    "leftImage": "assets/alphabets/W.png",
    "rightImage": "assets/alphabetsImages/whale.png",
    'soundPath': 'assets/phonicsSound/whale.mp3',
    "quizOptions": [
      {"text": "W", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "X",
    "leftImage": "assets/alphabets/X.png",
    "rightImage": "assets/alphabetsImages/xylophone.png",
    'soundPath': 'assets/phonicsSound/xylophone.mp3',
    "quizOptions": [
      {"text": "X", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "Y",
    "leftImage": "assets/alphabets/Y.png",
    "rightImage": "assets/alphabetsImages/yoyo.png",
    'soundPath': 'assets/phonicsSound/yoyo.mp3',
    "quizOptions": [
      {"text": "Y", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
  {
    "letter": "Z",
    "leftImage": "assets/alphabets/Z.png",
    "rightImage": "assets/alphabetsImages/zebra.png",
    'soundPath': 'assets/phonicsSound/zebra.mp3',
    "quizOptions": [
      {"text": "Z", "isCorrect": true},
      {"text": "B", "isCorrect": false},
      {"text": "C", "isCorrect": false},
    ],
  },
];
